# numpy

In [1]:
import numpy as np

In [3]:
lst = [1,2,3]
arr = np.array(lst)
arr

array([1, 2, 3])

In [4]:
type(lst)

list

In [5]:
len(lst)

3

In [7]:
arr.shape

(3,)

In [11]:
print(arr.shape)

(3, 3)


In [10]:
lst1 = [1,2,3]
lst2 = [3,4,5]
lst3 = [6,7,8]
arr = np.array([lst1,lst2,lst3])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr.reshape([3,3])

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#indexing
arr = np.array([1,2,34])
arr[2]

34

In [27]:
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
arr = np.arange(0,12,step=2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [30]:
#copy and broadcasting
arr[2:] = 100
arr

array([  0,   2, 100, 100, 100, 100])

In [31]:
arr1 = arr
arr1[2:] = 500
arr1

array([  0,   2, 500, 500, 500, 500])

In [32]:
#conditions
val = 2
arr<2

array([ True, False, False, False, False, False])

In [34]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones(3,dtype = int)

array([1, 1, 1])

In [37]:
np.random.rand(2,3)

array([[0.21254589, 0.62292213, 0.70309459],
       [0.40890434, 0.15423429, 0.41750251]])

# pandas

In [38]:
import pandas as pd

In [39]:
df = pd.DataFrame(np.arange(0,20)).reshape(5,4),index=['row1','row2','row3','row4','row5'],coloumns=['coloumns1','coloumns2','coloumns3','coloumns4']
df.head()

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (316903542.py, line 1)